### ISSUE TITLE
Uncaught ReferenceError: apiURL is undefined for gfycat links

### ISSUE THREAD

**Issue by heavyboots** [chrisfoley/lightboxe#3] opened 2016-05-05 17:12 UTC
Me again, lol. Seems like something is going wrong with the gfycat links—in the console they are throwing the error above and the lightbox just shows animated ellipses forever. 

Tested in both the latest Chrome and Vivaldi browsers.

**Comment by chrisfoley** [comment] 2016-05-07 01:15
@heavyboots Thanks for reporting. I'm pretty sure that this was caused by a server error in fetching the gfycat. All of the gfycats I've tested are still working, so maybe the one you were trying was  deleted, or maybe the site you were fetching it from was introducing an error. 

If you give me the site or the gfycat link, I can investigate further.

The reference error was not causing this problem, but it was a bug in the error handling code which I fixed with the latest version update. Now when there's a server error, you should see a proper error message and the loading gif will go away.

**Comment by heavyboots** [comment] 2016-05-07 03:04
Well now I feel a bit like an idiot. 

Your post made me revisit everything and after further testing, I discovered that it is the *Privacy Badger* extension that is blocking the GIFs when they're loaded via LightboxE. It was very confusing to me because if I clicked through and viewed them as a separate item, they worked perfectly, plus I could see an error popping up in the console.

Apologies! Still my favorite extension for simplifying Reddit browsing! :)

**Closed** 2016-05-07 03:05 UTC
